### ISSUE TITLE
reimporting the same key/value should be a no-op

### ISSUE THREAD

**Issue by max-mapper** [maxogden/dat-core#11]
e.g. if you import the same csv twice, the second time it should not affect any state on disk

another way to phrase it is: ignore subsequent key/value pairs that are the same

**Comment by mafintosh** [comment]
decoupling the commit data fixed this (assuming you import the same csv twice)

**Comment by max-mapper** [comment]
looks like this isn't quite fixed yet

![screen shot 2015-06-18 at 12 20 42 pm](https://cloud.githubusercontent.com/assets/39759/8240010/9808c674-15b4-11e5-9e3a-b4436e6df897.png)

thats after doing the same dat import twice (with `--key` set correctly)

**Comment by okdistribute** [comment]
@mafintosh is this still a problem?

**Comment by mafintosh** [comment]
Nope fixed!
