### ISSUE TITLE
visual differ

### ISSUE THREAD

**Issue by okdistribute** [maxogden/dat-core#2]
I'd like to start working on the visual differ, and I'm going to use this function which isn't implemented yet:

```
db.compare
```

At the R open sci unconference last weekend, there was a discussion/workshop on visual diffing from the user's perspective (thanks @karthik!). I took notes here: https://github.com/karissa/dat-visualdiff/issues/1 

I've been looking at multiple options and we could use `daff` for the html display side of a particular diff if we want. It's pretty bare bones, though, and requires that the user passes the data through like so:

starts with:

```
var data1 = [
    ['Country','Capital'],
    ['Ireland','Dublin'],
    ['France','Paris'],
    ['Spain','Barcelona']
];
var data2 = [
    ['Country','Code','Capital'],
    ['Ireland','ie','Dublin'],
    ['France','fr','Paris'],
    ['Spain','es','Madrid'],
    ['Germany','de','Berlin']
];
```

which you must turn into their 'highligher format'

```
[ [ '!', '', '+++', '' ],
  [ '@@', 'Country', 'Code', 'Capital' ],
  [ '+', 'Ireland', 'ie', 'Dublin' ],
  [ '+', 'France', 'fr', 'Paris' ],
  [ '->', 'Spain', 'es', 'Barcelona->Madrid' ],
  [ '+++', 'Germany', 'de', 'Berlin' ] ]
```

So what should `db.compare` output? Stick with daff-style formatting? allow it as an export option? What about very large dats? daff was made with little ones in mind.

Use cases that we can do that **daff does not do**:
- **filter by diff type** checking the first N rows to guess at the diff type. 
  - column-wise: if all the rows in the first N of a particular column have changed, the whole column has probably changed. people might want to filter out these columns, or 'approve changes' for an entire column so they can visually focus on the row-based changes.
  - spot-checking: what little changes have been made across the whole table?

**Comment by mafintosh** [comment]
Since this is dat-core the compare method wouldn't really diff the data. Like you say generic diffing is _hard_ so we should leave that up to a lot of different modules that can be used with compare. 

Instead it would simply return the keys and values of two branches that have "conflict potential" if those two branches where to be merged.

Say you have branch A that has `{key: 'foo', value: 'hello'}` and branch B that has `{key: 'foo', value: 'hi'}` the compare method you return both those two documents as there might be a potential conflict since the share the key `foo`. 

Now if branch A only contained `{key: 'bar', value: 'hello`}` the compare result would be empty as wouldn't be any potential clashes if the branches we're to be merged.

**Comment by mafintosh** [comment]
So to start doing the diffing method you should find a diff strategy you think is good and do the diffing yourself in your difftool. `db.compare` will probably return a list with elements like

``` js
{
  key: 'some key',
  values: [(value from branch A), (value from brach B)] 
}
```

**Comment by okdistribute** [comment]
Okay, this makes sense. 

Can we have more than just 'values' and 'key'? Is it possible to add in more metadata at some point down the road? (e.g., who changed it)

**Comment by okdistribute** [comment]
I guess the metadata would be in the "values", part, no? Or would it be in the branch information, that you'd have to look up separately?

Maybe it makes sense to have the 'values' list contain objects instead of tuples or strings, so that we can extend them with metadata if necessary, without breaking apis.

**Comment by okdistribute** [comment]
like 

``` js
{
  key: 'some key',
  values: [
    { 'branch': 'branchA', value: 'mars'},
    { 'branch': 'branchB', value: 'world'}
  ]
}
```

**Comment by mafintosh** [comment]
Makes sense. Lets add the keys in there as well to make it self describing

**Comment by okdistribute** [comment]
What do you think it'd output if a row's value is deleted?

**Comment by okdistribute** [comment]
also if added? `value: null` or something?

**Comment by mafintosh** [comment]
`value: null` sounds good and i'll add a `type: put | del` as well

**Comment by okdistribute** [comment]
great!

**Comment by okdistribute** [comment]
for semantic purposes maybe use 'changes' and 'row' instead of 'values' and 'value'

``` js
{
  key: 'some key',
  changes: [
    { 'branch': 'branchA', row: 'mars'},
    { 'branch': 'branchB', row: 'world'}
  ]
}
```

**Comment by mafintosh** [comment]
diffs are in master now \o/

**Comment by okdistribute** [comment]
Yeee ahh! I'll see if I can break it :-)

diffs are in master now \o/
