### ISSUE TITLE
dont hash timestamps

### ISSUE THREAD

**Issue by max-mapper** [maxogden/dat-core#24]
if you e.g. do the same merge twice on two separate machines, the hashes should match

basicalliy dont put timestamps in the graph

**Comment by ekg** [comment]
Where are the timestamps being kept?

**Comment by mafintosh** [comment]
@ekg right now they are in the graph nodes but we're just gonna put them in a local meta sublevel so they don't break hashing.

**Comment by ekg** [comment]
Cool I get it. Funny how quickly decisions like that make themselves heard.

**Comment by okdistribute** [comment]
nice catch

**Comment by karissa** [comment]
Fixing this raises an message, author, and timestamp seem like metadata of the commit

**Comment by okdistribute** [comment]
Fixing this reopens another issue. Now timestamps won't match at all and will become local, i.e., not part of the commit. This means:

user1: `dat import` on June 24, 2015
-- timestamp created at abcdef
user2: `dat pull` from user1 on December 1st, 2016
-- user2 will see user1's import with a timestamp of December 1st, 2016 for abcdef

This is confusing and we lose information about the original commit. By having timestamps local, however, dat will create the same hash if the same data is imported on different machines (with no message or author data). I can imagine some use cases without messages/authors/timestamps in the graph, where they could take advantage of merge strategies on different machines creating the same hashes. But in the open gov and data science use cases, having bad timestamps would be a disaster.

Although not ideal, it seems like fields like message, author, and timestamp should be hashed in the commit. These values would change with almost every operation every time, so a fork would be created if the exact same merge or import operation is performed on two different machines.

I'd vote having all data in the graph, but you could set a consistent hashing option. @mafintosh says it could just 0 all timestamps in the consistent hashing option. -- i.e. it would not have timestamps basically

**Comment by max-mapper** [comment]
OK we decided in IRC to revert this feature for now.

The reason is that we want to still support showing 'original timestamps' in the UI, and the graph isn't flexible enough at the moment to replicate metadata like that. it's easier if we just hash everything, replicate original timestamps, and deal with the extra merges that will happen as a result.
